# Generated by Django 4.0.1 on 2024-05-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0041_auto_20240525_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='brand',
            field=models.CharField(choices=[('Fiat', 'Fiat'), ('KIA', 'KIA'), ('BMW', 'BMW'), ('Opel', 'Opel'), ('Audi', 'Audi'), ('Renault', 'Renault')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='featured_image1',
            field=models.ImageField(blank=True, default='bmwcs.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advert',
            name='featured_image2',
            field=models.ImageField(blank=True, default='bmwcs.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advert',
            name='featured_image3',
            field=models.ImageField(blank=True, default='bmwcs.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='advert',
            name='first_registration',
            field=models.IntegerField(null=True),
        ),
    ]
