# Generated by Django 4.0.1 on 2024-06-01 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0042_alter_advert_brand_alter_advert_featured_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='city_fuel_consumption',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='advert',
            name='co2_emission',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='advert',
            name='combined_fuel_consumption',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='advert',
            name='eco_sticker',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='emission_class',
            field=models.CharField(blank=True, choices=[('Euro 1', 'Euro 1'), ('Euro 2', 'Euro 2'), ('Euro 3', 'Euro 3'), ('Euro 4', 'Euro 4'), ('Euro 5', 'Euro 5'), ('Euro 6', 'Euro 6')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='highway_fuel_consumption',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
