# Generated by Django 4.0.1 on 2024-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0043_advert_city_fuel_consumption_advert_co2_emission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='economy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
