# Generated by Django 4.0.1 on 2024-06-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0044_advert_economy'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='postal_code',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='street',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
