# Generated by Django 4.0.1 on 2024-06-03 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0045_advert_city_advert_postal_code_advert_street'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='address',
        ),
    ]
