# Generated by Django 4.0.1 on 2024-06-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0046_remove_advert_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='color_type',
            field=models.CharField(choices=[('Matowy', 'Matowy'), ('Metalik', 'Metalik'), ('Perłowy', 'Perłowy')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='num_of_doors',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], null=True),
        ),
    ]
