# Generated by Django 4.0.1 on 2024-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0047_alter_advert_color_type_alter_advert_num_of_doors'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='condition',
            field=models.CharField(choices=[('Używane', 'Używane'), ('Nowe', 'Nowe'), ('Poleasingowy', 'Poleasingowy')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='country_of_origin',
            field=models.CharField(choices=[('Austria', 'Austria'), ('Belgia', 'Belgia'), ('Białoruś', 'Białoruś'), ('Bułgaria', 'Bułgaria'), ('Chorwacja', 'Chorwacja'), ('Czechy', 'Czechy'), ('Dania', 'Dania'), ('Estonia', 'Estonia'), ('Finlandia', 'Finlandia'), ('Francja', 'Francja'), ('Grecja', 'Grecja'), ('Hiszpania', 'Hiszpania'), ('Holandia', 'Holandia'), ('Inny', 'Inny'), ('Irlandia', 'Irlandia'), ('Islandia', 'Islandia'), ('Japonia', 'Japonia'), ('Kanada', 'Kanada'), ('Korea', 'Korea'), ('Liechtenstein', 'Liechtenstein'), ('Litwa', 'Litwa'), ('Luksemburg', 'Luksemburg'), ('Łotwa', 'Łotwa'), ('Monako', 'Monako'), ('Niemcy', 'Niemcy'), ('Norwegia', 'Norwegia'), ('Polska', 'Polska'), ('Rosja', 'Rosja'), ('Rumunia', 'Rumunia'), ('Słowacja', 'Słowacja'), ('Słowenia', 'Słowenia'), ('USA', 'USA'), ('Szwajcaria', 'Szwajcaria'), ('Szwecja', 'Szwecja'), ('Turcja', 'Turcja'), ('Ukraina', 'Ukraina'), ('Węgry', 'Węgry'), ('Wielka Brytania', 'Wielka Brytania'), ('Włochy', 'Włochy')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='damaged',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='drive',
            field=models.CharField(choices=[('4x4 (dołączany automatycznie)', '4x4 (dołączany automatycznie)'), ('4x4 (dołączany ręcznie)', '4x4 (dołączany ręcznie)'), ('4x4 (stały)', '4x4 (stały)'), ('Na przednie koła', 'Na przednie koła'), ('Na tylne koła', 'Na tylne koła')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='first_owner',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='has_registration_number',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='imported',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='model',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='registered_as_antique',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='registered_in_poland',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='registration_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='right_hand_drive',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='serviced_in_aso',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='transmission',
            field=models.CharField(choices=[('Automatyczna', 'Automatyczna'), ('Manualna', 'Manualna')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='truck_approval',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='advert',
            name='tuning',
            field=models.CharField(choices=[('Tak', 'Tak'), ('Nie', 'Nie')], max_length=200, null=True),
        ),
    ]
