# Generated by Django 4.0.1 on 2024-06-03 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0049_alter_advert_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='advert',
            name='featured_image1',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='featured_image2',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='featured_image3',
        ),
        migrations.AddField(
            model_name='advert',
            name='images',
            field=models.ManyToManyField(blank=True, default='bmwcs.jpg', to='carapp.Image'),
        ),
    ]
