# Generated by Django 4.0.1 on 2024-06-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0050_image_remove_advert_featured_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='images',
            field=models.ManyToManyField(blank=True, to='carapp.Image'),
        ),
    ]
