# Generated by Django 4.0.1 on 2024-06-03 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0051_alter_advert_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='images',
        ),
        migrations.AddField(
            model_name='advert',
            name='featured_image1',
            field=models.ImageField(blank=True, default='bmwcs.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='advert',
            name='featured_image2',
            field=models.ImageField(blank=True, default='bmwcs.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='advert',
            name='featured_image3',
            field=models.ImageField(blank=True, default='bmwcs.jpg', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
