# Generated by Django 4.0.1 on 2024-06-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0052_remove_advert_images_advert_featured_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='featured_image4',
            field=models.ImageField(blank=True, default='bmwcs.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='advert',
            name='featured_image5',
            field=models.ImageField(blank=True, default='bmwcs.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='advert',
            name='featured_image6',
            field=models.ImageField(blank=True, default='bmwcs.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='advert',
            name='featured_image7',
            field=models.ImageField(blank=True, default='bmwcs.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='advert',
            name='featured_image8',
            field=models.ImageField(blank=True, default='bmwcs.jpg', null=True, upload_to=''),
        ),
    ]
