# Generated by Django 4.0.1 on 2024-06-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0053_advert_featured_image4_advert_featured_image5_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ABS', 'ABS'), ('Elektroniczny system rozdziału sił hamowania', 'Elektroniczny system rozdziału sił hamowania'), ('Asystent hamowania awaryjnego', 'Asystent hamowania awaryjnego'), ('Aktywny asystent hamowania w mieście', 'Aktywny asystent hamowania w mieście'), ('System ostrzegania o zmęczeniu kierowcy', 'System ostrzegania o zmęczeniu kierowcy'), ('System ostrzegania o możliwości kolizji', 'System ostrzegania o możliwości kolizji'), ('System chroniący przed uderzeniami bocznymi', 'System chroniący przed uderzeniami bocznymi'), ('System chroniący przed uderzeniami tylnymi', 'System chroniący przed uderzeniami tylnymi'), ('System eliminujący dźwięk silnika (AVAS)', 'System eliminujący dźwięk silnika (AVAS)'), ('Alarm ruchu poprzecznego z tyłu', 'Alarm ruchu poprzecznego z tyłu'), ('Asystent utrzymania pasa ruchu podczas trasy', 'Asystent utrzymania pasa ruchu podczas trasy'), ('Asystent wykrywania przeszkód kierowcy', 'Asystent wykrywania przeszkód kierowcy'), ('System rekompensacji przechyłów bocznych w zakrętach (DSC)', 'System rekompensacji przechyłów bocznych w zakrętach (DSC)'), ('System minimalizowania skutków kolizji tylnych (CMS)', 'System minimalizowania skutków kolizji tylnych (CMS)'), ('Poduszka powietrzna centralna', 'Poduszka powietrzna centralna'), ('Boczna poduszka powietrzna kierowcy', 'Boczna poduszka powietrzna kierowcy'), ('Boczne poduszki powietrzne - przód', 'Boczne poduszki powietrzne - przód'), ('Kurtyny powietrzne - tył', 'Kurtyny powietrzne - tył'), ('Boczne poduszki powietrzne - tył', 'Boczne poduszki powietrzne - tył'), ('Kurtyna powietrzna z tyłu, ochrona głowy', 'Kurtyna powietrzna z tyłu, ochrona głowy'), ('Poduszka powietrzna pasażera bezpieczeństwa', 'Poduszka powietrzna pasażera bezpieczeństwa'), ('Isofix (punkty mocowania fotelika dziecięcego)', 'Isofix (punkty mocowania fotelika dziecięcego)'), ('System zabezpieczenia pojazdu podczas dachowania', 'System zabezpieczenia pojazdu podczas dachowania')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tuning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Opony runflat', 'Opony runflat'), ('Zawieszenie komfortowe', 'Zawieszenie komfortowe'), ('Elektroniczna regulacja charakterystyki zawieszenia', 'Elektroniczna regulacja charakterystyki zawieszenia'), ('Zawieszenie sportowe', 'Zawieszenie sportowe'), ('Zawieszenie regulowane', 'Zawieszenie regulowane'), ('Zawieszenie pneumatyczne', 'Zawieszenie pneumatyczne'), ('Zawieszenie hydropneumatyczne', 'Zawieszenie hydropneumatyczne'), ('Hamulce z kompozytów ceramicznych', 'Hamulce z kompozytów ceramicznych'), ('Filtr cząstek stałych', 'Filtr cząstek stałych')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='advert',
            name='tuning',
        ),
        migrations.AddField(
            model_name='advert',
            name='safety',
            field=models.ManyToManyField(blank=True, to='carapp.Safety'),
        ),
        migrations.AddField(
            model_name='advert',
            name='tuning',
            field=models.ManyToManyField(blank=True, to='carapp.Tuning'),
        ),
    ]
