# Generated by Django 4.0.1 on 2024-06-19 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0057_advert_active_lane_change_assistant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 15, 8, 19, 270722, tzinfo=utc)),
        ),
    ]
