# Generated by Django 4.0.1 on 2024-06-19 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0058_advert_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 19, 19, 41, 59, 955236, tzinfo=utc)),
        ),
    ]
