# Generated by Django 4.0.1 on 2024-06-20 11:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0060_alter_advert_expiry_date_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='advert',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 11, 25, 19, 179581, tzinfo=utc)),
        ),
    ]
