# Generated by Django 4.0.1 on 2024-06-20 11:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0061_notification_is_new_alter_advert_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 20, 11, 27, 12, 573091, tzinfo=utc)),
        ),
    ]
