# Generated by Django 4.0.1 on 2024-06-21 00:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0063_remove_notification_is_new_alter_advert_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='economy_auto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advert',
            name='for_family',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advert',
            name='sport',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='advert',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 0, 41, 39, 879670, tzinfo=utc)),
        ),
    ]
