# Generated by Django 4.0.1 on 2024-06-21 00:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0064_advert_economy_auto_advert_for_family_advert_sport_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 0, 42, 50, 64639, tzinfo=utc)),
        ),
    ]
