# Generated by Django 4.0.1 on 2024-06-21 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0066_advert_advanced_safety_systems_advert_comfortable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='intelligent',
        ),
        migrations.AlterField(
            model_name='advert',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 9, 29, 56, 911985, tzinfo=utc)),
        ),
    ]
