# Generated by Django 4.0.1 on 2024-06-21 09:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0067_remove_advert_intelligent_alter_advert_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 9, 34, 51, 327205, tzinfo=utc)),
        ),
    ]
