# Generated by Django 4.0.1 on 2024-06-21 10:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0071_rename_advanced_safety_systems_advert_safety_systems_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 21, 10, 19, 46, 737354, tzinfo=utc)),
        ),
    ]
